### ISSUE TITLE
Часть тайтлов не работает - не генерируется epub (модуль epub-gen)

### ISSUE THREAD

**Issue by banditto9** [ryadik/ranobelib-parser#2]
Добрый день, благодарю за труды и исправление первого issue.
Стало лучше, но на больших, многотомных тайтлах все равно вываливается на epub-gen, насколько я могу судить.
На некоторых тайтлах работает без вопросов - т.е. по-прежнему "лотерея" и не знаешь получится или нет..
Нет возможности заменить эту библиотеку epub-gen? - судя по источнику, она весьма старая и давно не обновлялась.
Спасибо!

Пример ошибки 1 (Debian 12.2):

archie@debian:~/tools/ranobelib-parser-feature-typescript$ npm install
archie@debian:~/tools/ranobelib-parser-feature-typescript$ npm run build
archie@debian:~/tools/ranobelib-parser-feature-typescript$ npm start
Здравствуйте, это программа загрузки книг с сайта ranobelib.me
Пожалуйста, прочитайте информацию ниже.

Во время загрузки у Вас, несколько раз, будет открываться и закрываться окно браузера.
Пожалуйста, не беспокойтесь, так и должно быть.
Во время загрузки, пожалуйста, не трогайте окно браузера, это может привести к сбоям.

Введите, пожалуйста, адрес книги с сайта ranobelib.me
Пример адреса: https://ranobelib.me/sakurasou-no-pet-na-kanojo-novel
Пожалуйста, указывайте верный адрес, во избежания проблем с работой программы.
https://ranobelib.me/violet-evergarden-novel

Сейчас начнется загрузка книги, по адресу: https://ranobelib.me/violet-evergarden-novel

Получение информации о книге...

Получение списка глав...

Загрузка всех глав книги, поочередно...

Генерация книги violet-evergarden-novel.epub в папке books/

/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/epub-gen/lib/index.js:169
            mediaType = mime.getType(url.replace(/\?.*/, ""));
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/epub-gen/lib/index.js:169:42)
    at exports.each (/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/cheerio/lib/api/traversing.js:300:24)
    at /home/archie/tools/ranobelib-parser-feature-typescript/node_modules/epub-gen/lib/index.js:159:18
    at Function.map (/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/underscore/underscore-node-f.cjs:1342:22)
    at new EPub (/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/epub-gen/lib/index.js:95:32)
    at BookService.generateEpubFromData (/home/archie/tools/ranobelib-parser-feature-typescript/build/services/BookService/index.js:101:16)
    at /home/archie/tools/ranobelib-parser-feature-typescript/build/index.js:50:45

Node.js v21.2.0
archie@debian:~/tools/ranobelib-parser-feature-typescript$ 

------------------------------------------------------------------------------------------------

Пример ошибки 2 (Windows 10 22H2):

PS D:\BOOKS\non-lib\ranobelib-parser> npm start
Здравствуйте, это программа загрузки книг с сайта ranobelib.me
Пожалуйста, прочитайте информацию ниже.

Во время загрузки у Вас, несколько раз, будет открываться и закрываться окно браузера.
Пожалуйста, не беспокойтесь, так и должно быть.
Во время загрузки, пожалуйста, не трогайте окно браузера, это может привести к сбоям.

Введите, пожалуйста, адрес книги с сайта ranobelib.me
Пример адреса: https://ranobelib.me/sakurasou-no-pet-na-kanojo-novel
Пожалуйста, указывайте верный адрес, во избежания проблем с работой программы.
https://ranobelib.me/dokusha-boku-to-shujinkou-kanojo-to-futari-no-korekara

Сейчас начнется загрузка книги, по адресу: https://ranobelib.me/dokusha-boku-to-shujinkou-kanojo-to-futari-no-korekara

Получение информации о книге...

Получение списка глав...

Загрузка всех глав книги, поочередно...

Генерация книги dokusha-boku-to-shujinkou-kanojo-to-futari-no-korekara.epub в папке books/

D:\BOOKS\non-lib\ranobelib-parser\node_modules\epub-gen\lib\index.js:169
            mediaType = mime.getType(url.replace(/\?.*/, ""));
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (D:\BOOKS\non-lib\ranobelib-parser\node_modules\epub-gen\lib\index.js:169:42)
    at exports.each (D:\BOOKS\non-lib\ranobelib-parser\node_modules\cheerio\lib\api\traversing.js:300:24)
    at D:\BOOKS\non-lib\ranobelib-parser\node_modules\epub-gen\lib\index.js:159:18
    at Function.map (D:\BOOKS\non-lib\ranobelib-parser\node_modules\underscore\underscore-node-f.cjs:1342:22)
    at new EPub (D:\BOOKS\non-lib\ranobelib-parser\node_modules\epub-gen\lib\index.js:95:32)
    at BookService.generateEpubFromData (D:\BOOKS\non-lib\ranobelib-parser\build\services\BookService\index.js:101:16)
    at D:\BOOKS\non-lib\ranobelib-parser\build\index.js:50:45

Node.js v20.9.0
PS D:\BOOKS\non-lib\ranobelib-parser>

------------------------------------------------------------------------------------------------

пример отработавшего тайтла (Debian 12.2):

archie@debian:~/tools/ranobelib-parser-feature-typescript$ npm start
Здравствуйте, это программа загрузки книг с сайта ranobelib.me
Пожалуйста, прочитайте информацию ниже.

Во время загрузки у Вас, несколько раз, будет открываться и закрываться окно браузера.
Пожалуйста, не беспокойтесь, так и должно быть.
Во время загрузки, пожалуйста, не трогайте окно браузера, это может привести к сбоям.

Введите, пожалуйста, адрес книги с сайта ranobelib.me
Пример адреса: https://ranobelib.me/sakurasou-no-pet-na-kanojo-novel
Пожалуйста, указывайте верный адрес, во избежания проблем с работой программы.
https://ranobelib.me/cherry-leaves-and-the-flute

Сейчас начнется загрузка книги, по адресу: https://ranobelib.me/cherry-leaves-and-the-flute

Получение информации о книге...

Получение списка глав...

Загрузка всех глав книги, поочередно...

Генерация книги cherry-leaves-and-the-flute.epub в папке books/

Generating Template Files.....

Книга успешно добавлена в папку book/

Приятного чтения!
EPub {
  options: {
    description: 'Листья вишни и флейта (Новелла)',
    publisher: 'anonymous',
    author: [ 'Osamu Dazai' ],
    tocTitle: 'Содержание',
    appendChapterTitles: true,
    date: '2023-11-20T09:00:45.791Z',
    lang: 'ru',
    fonts: [],
    customOpfTemplatePath: null,
    customNcxTocTemplatePath: null,
    customHtmlTocTemplatePath: null,
    version: 3,
    title: 'Листья вишни и флейта (Новелла)',
    cover: 'https://cover.imglib.info/uploads/cover/cherry-leaves-and-the-flute/cover/h8xjaRZSuEPQ_250x350.jpg',
    content: [ [Object] ],
    output: '/home/archie/tools/ranobelib-parser-feature-typescript/build/../books/cherry-leaves-and-the-flute.epub',
    verbose: true,
    docHeader: '<?xml version="1.0" encoding="UTF-8"?>\n' +
      '<!DOCTYPE html>\n' +
      '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="ru">',
    tempDir: '/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/epub-gen/tempDir',
    uuid: '/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/epub-gen/tempDir/241a4237-eb6f-4c0c-b9aa-07d3a50dd5f5',
    id: '241a4237-eb6f-4c0c-b9aa-07d3a50dd5f5',
    images: [],
    _coverMediaType: 'image/jpeg',
    _coverExtension: 'jpeg',
    css: <Buffer 2e 65 70 75 62 2d 61 75 74 68 6f 72 20 7b 0a 20 20 20 20 63 6f 6c 6f 72 3a 20 23 35 35 35 3b 0a 7d 0a 0a 2e 65 70 75 62 2d 6c 69 6e 6b 20 7b 0a 20 20 ... 288 more bytes>
  },
  defer: defer {
    promise: Promise {
      promiseDispatch: [Function (anonymous)],
      valueOf: [Function (anonymous)],
      inspect: [Function (anonymous)]
    },
    resolve: [Function (anonymous)],
    fulfill: [Function (anonymous)],
    reject: [Function (anonymous)],
    notify: [Function (anonymous)]
  },
  id: '241a4237-eb6f-4c0c-b9aa-07d3a50dd5f5',
  uuid: '/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/epub-gen/tempDir/241a4237-eb6f-4c0c-b9aa-07d3a50dd5f5',
  promise: Promise {
    promiseDispatch: [Function (anonymous)],
    valueOf: [Function (anonymous)],
    inspect: [Function (anonymous)]
  }
}
Downloading Images...
Making Cover...
[Success] cover image downloaded successfully!
Generating Epub Files...
Zipping temp dir to /home/archie/tools/ranobelib-parser-feature-typescript/build/../books/cherry-leaves-and-the-flute.epub
Done zipping, clearing temp dir...
About to finish...
Done.
archie@debian:~/tools/ranobelib-parser-feature-typescript$

**Comment by Harurunya** [comment]
после "отката" клонирована мастер ветка.
и опять
на той же книге та же самая ошибка

(https://ranobelib.me/tsuki-ga-michibiku-isekai-douchuu-novel)

Генерация книги tsuki-ga-michibiku-isekai-douchuu-novel.epub в папке books/ 

S:\1\node_modules\epub-gen\lib\index.js:169
            mediaType = mime.getType(url.replace(/\?.*/, ""));
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (S:\1\node_modules\epub-gen\lib\index.js:169:42)
    at exports.each (S:\1\node_modules\cheerio\lib\api\traversing.js:300:24)
    at S:\1\node_modules\epub-gen\lib\index.js:159:18
    at Function.map (S:\1\node_modules\underscore\underscore-node-f.cjs:1342:22)
    at new EPub (S:\1\node_modules\epub-gen\lib\index.js:95:32)
    at generateEpubFromData (file:///S:/1/src/index.js:193:9)
    at file:///S:/1/src/index.js:228:9

Node.js v21.1.0

Для продолжения нажмите любую клавишу . . .

а так же точно такая же ошибка в версии парсера с  typescript

**Comment by K1nGsmaN-hub** [comment]
привет! спасибо за репорт. сейчас много работы поэтому нет времени сесть за этот проект. ближе к концу декабря попробую что-нибудь придумать. либа действительно старая, так что я думал написать свой генератор.
пока к сожалению действительно "лотерея" :(

**Comment by Harurunya** [comment]
пока к сожалению действительно "лотерея" :(

а на что может ругаться 

mediaType = mime.getType(url.replace(/?.*/, ""));
и Cannot read properties of undefined (reading 'replace')
может в этом самом реплейсе какая то ошибка
что и на что вообще он заменяет.

(/?.*/, "") вот конкретно эти символы. 

может что то не так с их порядком пунктуацией или еще чем
не спроста же оно в каждой ошибке именно с этого начинает.

а так же 
если оно относится к генерации обложек или еще чего
почему бы просто не отключить собственно эту. генерацию

          } else {
            id = uuid();
            mediaType = mime.getType(url.replace(/\?.*/, ""));
            extension = mime.getExtension(mediaType);
            dir = content.dir;
            self.options.images.push({id, url, dir, mediaType, extension});
          }

моих познаний в JS не достаточно но разве это не относится к обложкам/артам/картинкам
если так то можно было бы просто убрать обложки/иллюстрации с генератора как временную меру,

**Comment by ryadik** [comment]
да, скорее всего проблема с получением изображения, но в этой либе обязательно нужно передавать изображение.

**Comment by obezglavlen** [comment]
> ладно. перехожу в режим ожидания правок и апдейтов) спасибо за ответы.

Привет, дождался) Можеш пока что склонить ветку `feature/typescript` [отсюда](https://github.com/obezglavlen/ranobelib-parser), должно работать. 
Как автор примет пул реквест, удалю форк у себя

**Comment by banditto9** [comment]
Привет и спасибо за время и труды, у меня не взлетает... 
Перекатился на https://github.com/OnlyFart/Elib2Ebook - скомпилирован в exe, работает без открытия браузера, советую двумя руками!

archie@debian:~/tools/ranobelib-parser-feature-typescript$ ./start.sh
Здравствуйте, это программа загрузки книг с сайта ranobelib.me
Пожалуйста, прочитайте информацию ниже.

Во время загрузки у Вас, несколько раз, будет открываться и закрываться окно браузера.
Пожалуйста, не беспокойтесь, так и должно быть.
Во время загрузки, пожалуйста, не трогайте окно браузера, это может привести к сбоям.

Введите, пожалуйста, адрес книги с сайта ranobelib.me
Пример адреса: https://ranobelib.me/sakurasou-no-pet-na-kanojo-novel
Пожалуйста, указывайте верный адрес, во избежания проблем с работой программы.
https://ranobelib.me/violet-evergarden-novel

Сейчас начнется загрузка книги, по адресу: https://ranobelib.me/violet-evergarden-novel

Получение информации о книге...

Получение списка глав...
/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:59
                void this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
                                    ^

TimeoutError: Waiting for selector `div.team-list` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/home/archie/tools/ranobelib-parser-feature-typescript/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:59:37)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v21.2.0

**Comment by obezglavlen** [comment]
@banditto9, спасибо за фидбек, вроде пофиксил

**Comment by ryadik** [comment]
@obezglavlen Привет! Спасибо за пулл-реквесты. Только щас руки дошли, все посмотреть)
Вмержил тайпскрипт в мастер. Протестил, вроде все нормально.🤔
